In [223]:
import pandas as pd
import numpy as np

In [255]:
base = pd.read_csv('census.csv')
base.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [105]:
colunas = ['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country']

df_previsores.columns = colunas

In [256]:
## Criando variavel previsores

previsores = base.iloc[:, 0:14].values

## Criando variavel classe
classe = base.iloc[:, 14].values

In [257]:
## Transformacao das variaveis categorias em numericas 
## Algoritmos de Machine Learning nao trabalham bem com variaveis categoricas

from sklearn.preprocessing import LabelEncoder
labelencoder_previsores = LabelEncoder()
##labels = labelencoder_previsores.fit_transform(previsores[:,1])

previsores[:,1] = labelencoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
previsores[:,6] = labelencoder_previsores.fit_transform(previsores[:,6])
previsores[:,7] = labelencoder_previsores.fit_transform(previsores[:,7])
previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
previsores[:,13] = labelencoder_previsores.fit_transform(previsores[:,13])

## Criando variaveis do tipo DUMMY

In [311]:
## Devido às classificacoes, necessario criar colunas com 0 e 1
## Por exemplo: Se houver 3 categorias: 1 - branco, 2 - Negro, 3 - Indio
## O algoritimo pode entender que 3 > 2 > 1, quando na verdade, sao variaveis ordinais
## Portanto, serao criadas 3 colunas --> uma coluna para branco, uma coluna para negro e uma coluna para indio, sendo
## 0 para verdadeiro e 1 para falso

##from sklearn.preprocessing import LabelEncoder, OneHotEncoder

## default == all
## 8 == a coluna raça é a 8 no DataFrame

##previsores = base.iloc[:,8:9].values
## previsores[:,0] = labelencoder_previsores.fit_transform(previsores[:,0])

## onehotencoder = OneHotEncoder(categories=[0])

## previsores = onehotencoder.fit_transform(previsores).toarray()

In [310]:

#previsores[:,0] = labelencoder_previsores.fit_transform(previsores[:,0])
# previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
# previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
# previsores[:,6] = labelencoder_previsores.fit_transform(previsores[:,6])
# previsores[:,7] = labelencoder_previsores.fit_transform(previsores[:,7])
# previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
# previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
#previsores[:,13] = labelencoder_previsores.fit_transform(previsores[:,13])

In [291]:
previsores[0:,0]

array([4, 4, 4, ..., 4, 4, 4], dtype=object)

In [313]:
import pandas as pd

base = pd.read_csv('census.csv')

previsores = base.iloc[:, 0:14].values
classe = base.iloc[:, 14].values
                
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_previsores = LabelEncoder()

onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])],
                                   remainder='passthrough')
previsores = onehotencorder.fit_transform(previsores).toarray()

In [318]:
df_previsores = pd.DataFrame(previsores)
df_previsores

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
0,-0.24445,-0.174295,-0.262097,-0.014664,-1.516792,-0.188389,-0.290936,4.907700,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,-0.24445,-0.174295,-0.262097,-0.014664,-1.516792,-0.188389,3.437186,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,-2.932948,-0.045408,-0.022173,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-0.24445,-0.174295,-0.262097,-0.014664,0.659286,-0.188389,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,-0.24445,-0.174295,-0.262097,-0.014664,-1.516792,5.308156,-0.290936,-0.203761,-0.02074,-0.171753,...,-0.024163,0.340954,-0.045408,-0.022173,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

## Escalonamento dos valores

In [316]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

previsores = scaler.fit_transform(previsores)

In [321]:
from sklearn.model_selection import train_test_split

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size = 0.15, random_state =0)

In [323]:
previsores_treinamento.shape[0]

27676

In [324]:
previsores_teste.shape[0]

4885

In [325]:
classe_treinamento.shape[0]

27676

In [326]:
classe_teste.shape[0]

4885